# Generated by Django 4.1.2 on 2022-11-07 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_customer_age_alter_customer_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cinema_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip', models.CharField(blank=True, max_length=100, null=True)),
                ('cinema_email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('movie_title', models.CharField(blank=True, max_length=50, null=True)),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cinema')),
            ],
        ),
    ]
