# Generated by Django 4.1.2 on 2022-11-07 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_cinema_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField(blank=True, null=True)),
                ('end_time', models.IntegerField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.movie')),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='cinema_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Concession_stand',
            fields=[
                ('station_number', models.IntegerField(primary_key=True, serialize=False)),
                ('menu', models.CharField(blank=True, max_length=250, null=True)),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('show_time_movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.show_time')),
                ('seat_number', models.IntegerField(blank=True, null=True)),
                ('row_letter', models.CharField(blank=True, max_length=2, null=True)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.customer')),
            ],
        ),
    ]
