# Generated by Django 4.1.2 on 2022-11-07 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_show_time_cinema_cinema_phone_concession_stand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='show_time_movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.show_time'),
        ),
    ]
