# Generated by Django 4.1.2 on 2022-11-07 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_ticket_id_alter_ticket_show_time_movie_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction_receipt',
            fields=[
                ('transaction_number', models.IntegerField(primary_key=True, serialize=False)),
                ('receipt', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('items', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.IntegerField(primary_key=True, serialize=False)),
                ('items_ordered', models.CharField(blank=True, max_length=250, null=True)),
                ('pick_up_time', models.IntegerField(blank=True, null=True)),
                ('concession_stand_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.concession_stand')),
                ('customer_account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.customer')),
            ],
        ),
    ]
