# Generated by Django 4.1.3 on 2022-11-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_transaction_receipt_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='classification',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='row_letter',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='1', null=True),
        ),
    ]
