# Generated by Django 4.1.3 on 2022-11-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_ticket_classification_alter_ticket_row_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.FloatField(blank=True, choices=[(10.0, 'Adult Ticket $10.00'), (5.0, 'Kid Ticket $5.00')], default='----', null=True),
        ),
    ]
