# Generated by Django 4.1.3 on 2022-11-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_ticket_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='date',
        ),
    ]
