# Generated by Django 4.1.3 on 2022-11-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_show_time_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show_time',
            name='end_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='show_time',
            name='start_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
